### ISSUE TITLE
Critical: failing `ss.client.send` on `templateEngine.use` in 0.4.x

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream#534]
This is true for the `ss-hogan` and `ss-ractive`—both work in 0.3.x, but stopped working correctly in 0.4x:

```shell
/.../node_modules/ss-hogan/engine.js:11
  ss.client.send('lib', 'hogan-template', clientCode);
           ^
TypeError: Cannot read property 'send' of undefined
```

I know partially what's going on here, but not *why*. Note this line: https://github.com/socketstream/socketstream/blob/1136dd4163a9e134f349ef6c21cda327d7c31ba4/lib/client/template_engine.js#L79 and this line: https://github.com/socketstream/socketstream/blob/1136dd4163a9e134f349ef6c21cda327d7c31ba4/lib/client/template_engine.js#L79
If I run `console.log('nameOrModule');` it outputs `object`—which I don't think is right. Essentially, something got lost in transition, and `ss` is not being passed to the template engine.

Investigating further, and I'll probably do a PR on this issue since it breaks SS.

**Comment by thepian** [comment]
If you don't find it I will try to write unit tests for 'ss.client.send' to track it down. Shouldn't be hard.

**Comment by arxpoetica** [comment]
This appears to be the breaking change: https://github.com/socketstream/socketstream/commit/9bfdad5a84df1e3fdd74e6f2c9de697af4e06968#diff-e0f3678f754a6146e6e9109a7830a48fL96

Essentially, `init` was passed `ss` in the past, but is now conditionally passed `ss.root` in the case where `typeof mod` is not a function.

*Most* of the current template wrappers (ss-jade, ss-hogan, ss-ractive, ss-coffekup) have `init` set to a function, but leave the main module alone (which translates to `typeof mod === 'object'`), so either:

a) most of the template wrappers will need to rewrite their wrappers to access `ss` OR

b) we change this back to what it was

I admit I'm on the fence about this since the current implementation is more inline w/ the formatters API, bringing them inline. Thoughts?

For the time being, I'm just going to change my local ss-ractive version (since that's what I'm working off of at the moment), and wait for input.

**Comment by arxpoetica** [comment]
(
for reference:

https://github.com/socketstream/ss-jade/blob/master/wrapper.js#L6
https://github.com/socketstream/ss-hogan/blob/master/engine.js#L7
https://github.com/socketstream/ss-ractive/blob/master/engine.js#L7
https://github.com/socketstream/ss-coffeekup/blob/master/engine.js#L5
)

**Comment by thepian** [comment]
Could it be that the template engine is created before `ss.client` is assigned ?

**Comment by thepian** [comment]
Ah, I mistook the API for being like formatter

**Comment by arxpoetica** [comment]
@thepian right, they're technically different. I think they should be the same/similar, though. Thoughts? I think I'd rather have a breaking change and make them the same.

**Comment by thepian** [comment]
Nothing should be changed from before, it was my mistake copying things around. I never wrote a template engine before, so I didn't know any better. It's fixed now, will do a release.

In 0.4 we also support a simpler API for formatters and template_engine. Instead of making an object with an init function, the formatter or engine is that same function. In both cases the first parameter is the Socketstream API.

**Comment by thepian** [comment]
Try `npm install` now

**Comment by arxpoetica** [comment]
Cool & thx.

**Comment by thepian** [comment]
https://github.com/socketstream/socketstream/commit/19510e350cb7a8e0cf70b749ee8c0b3c5def2d7f
